import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { ClerkProvider, ClerkLoaded, ClerkLoading } from "@clerk/nextjs";
import Navbar from "@/components/Navbar";
import FooterWithPopups from "@/components/Footer";
import { dark } from "@clerk/themes";
import { Toaster } from "@/components/ui/toaster";
const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "threads ",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider appearance={{ baseTheme: dark }}>
      <html lang="en">
        <body
          className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        >
          <ClerkLoading>
            <div className="flex items-center justify-center h-screen text-2xl animate-pulse">
              <div className="terminal-loader">
                <div className="terminal-header">
                  <div className="terminal-title">Status</div>
                  <div className="terminal-controls">
                    <div className="control close"></div>
                    <div className="control minimize"></div>
                    <div className="control maximize"></div>
                  </div>
                </div>
                <div className="text">Loading...</div>
              </div>
            </div>
          </ClerkLoading>
          <ClerkLoaded>
            <Navbar />
            <div className="max-w-6xl mx-auto">
              <div className="flex flex-col h-screen">
                <Toaster />
                {children}{" "}
              </div>
            </div>
            <FooterWithPopups />
          </ClerkLoaded>
        </body>
      </html>
    </ClerkProvider>
  );
}
